### ISSUE TITLE
initialValue in list is throwing infinite loop with error "Maximum update depth exceeded...."

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/list-atom#10]
**Describe the bug**
initialValue in list is throwing infinite loop with error "Maximum update depth exceeded...."

**To Reproduce**
1. Go to List compoennt and add initialValue = (someValidList || fallbackList) as conditional statement
2. This throws error in console "Maximum update depth exceeded...."

**Expected behavior**
Like other fields (string, selectField), we need to get this working because we always have api call which makes atleSt 2 phases

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Try adding conditional statement

**Comment by MiroslavPetrik** [comment]
Hey, I believe this works as designed - the useFieldInitialValue does only a shallow equal, so I believe that when you set something like

`<List initialValue={[{value: 1}, {value: 2}]} />`
where there is always a new instance of the array, it will result in useEffect being called, which triggers render, which agains triggers the use effect and so on...

Again, the main purpose of the `initialValue` prop is to set a data received most of the time from the server, so usually its cached, e.g. if you use `react-query` that does the caching, or if you initialize only once, e.g. in NextJS.

if you need to set a custom static data, you need to persist that in a useState:

```tsx
const Example = () => {
  // data persisted between renders
  const [initialValue] = useState([{value: 1}, {value: 2}]);

  return <List initialValue={initialValue} />
```
