### ISSUE TITLE
Error "Writing unsupported value to listFieldAtom value!" for action.setValue()

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/list-atom#11]
**Describe the bug**
Hello @MiroslavPetrik  I am getting below error for list field when using this snippet
`action.setValue((prev)=> [...prev, { val: ''}])`

Full example as below:
```
  const actions = useFieldActions(fields.values);
  const add = () => {
    actions.setValue((prevList) => [...prevList, { value: '' }]);
  };
  const remove = () => {
    actions.setValue((prevList) => {
      prevList.slice(0, -1);
    });
  };
```
![Screenshot 2024-09-11 at 11 39 15 PM](https://github.com/user-attachments/assets/2c33dc0c-6cf4-4178-b3d1-485f66e6ccd2)

**To Reproduce**
1. Use action.setValue(callback) in setting the listField
2. Notice the error
3. Value will not be set

**Expected behavior**

**Screenshots**
![Screenshot 2024-09-11 at 11 39 15 PM](https://github.com/user-attachments/assets/c84ebbb9-f849-47cb-8709-8855ec999239)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by MiroslavPetrik** [comment]
Hello @pgangwani, thanks for opening the issue.

Currently there is no support for the callback parameter into the setter of the value atom:
https://github.com/form-atoms/list-atom/blob/d5f1e44213430a8b4a85884cbdf9233246ff78d9/src/atoms/list-atom/listAtom.ts#L231

Good catch, I believe this should be supported, given that its common behavior for jotai atoms.

**Comment by pgangwani** [comment]
Amazing @MiroslavPetrik  . Thanks alot will give it a test
