### ISSUE TITLE
Feature: Need ability to add/remove multiple items in list/Array

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/list-atom#4]
**Is your feature request related to a problem? Please describe.**
I have usecase of adding multiple items from previous field to list and remove multiple / all options.

**Describe the solution you'd like**
I would like to have few more hooks/function from renderProps(children) 

**Describe alternatives you've considered**
For now, I have to do forEach and call add/remove function from render prop

**Additional context**
Pls let me know if you need further details

**Comment by MiroslavPetrik** [comment]
I believe this can be done with `initialValue` prop, which will reinitialize the list for you.

**Comment by pgangwani** [comment]
Initial value fine. But after that there need a capability to remove all if required in a single button or action and similarly adding bulk instead of just one. Hope this adds more context ! Let me know If I am missing something.

**Comment by MiroslavPetrik** [comment]
You should use the `setValue` action from `useFieldActions`. See example for more https://form-atoms.github.io/list-atom/?path=/docs/components-list--docs#programmatically-set-value.

If you need to "append" multiple values to the current ones, or prepend etc, first read your list value with `useFieldValue` and pass it to the `setValue` combined with your new items.
