### ISSUE TITLE
Doc: how to achieve `AddButton` as part of last item

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/list-atom#5]
**Is your feature request related to a problem? Please describe.**
I have requirement to have `AddButton` as part of last index item. But with current implementation AddButton's placement is hardcoded. Below is illustration:
![image](https://github.com/form-atoms/list-atom/assets/14316332/f12447f6-059a-476a-818e-4c2d72086c22)

Additionally I would like to bind max index 1 (n) and min index 2(n+1) to have 2 way data binding with single atom. Meaning if I edit max1, min2 should be updated and vice versa

**Describe the solution you'd like**
Make AddButton configurable and default no AddButton if props is not passed

**Describe alternatives you've considered**
I have only one alternative to have value copied and concat, no other option as of now. Thanks to @MiroslavPetrik  for helping me learn 

**Additional context**

**Comment by MiroslavPetrik** [comment]
> But with current implementation AddButton's placement is hardcoded

You can use the `useListActions(myListAtom)` hook, which has `add` action. Use this action anywhere.

I've added example for this useful case, also displaying the add/remove actions only for the last item:
https://form-atoms.github.io/list-atom/?path=/docs/components-list--docs#positioning-add-button

>  Make AddButton configurable and default no AddButton if props is not passed

For now, you can disable the default button by setting the prop to render empty fragment:
 ```tsx
<List AddButton={() => <></>} />
```

Also for the add functionality, there is a new demo for **prepend** which is supported within the list and might be useful
https://form-atoms.github.io/list-atom/?path=/docs/components-list--docs#prepend

I don't have time to go into the min/max bindings for now. perhaps jotai-effect could be effective here.
