### ISSUE TITLE
Typescript : initialValues should have RESET allowed 

### ISSUE THREAD

**Issue by pgangwani** [form-atoms/list-atom#8]
**Describe the bug**
I noticed that List component has missing type to accept RESET symbol.

**To Reproduce**
1. Create <List ..> 
2. Add prop initialValue={RESET} in case of 
3. See the ts error 

**Expected behavior**
Like initialValue in useList(,{initialValue}), it should accept RESET symbol.

**Screenshots**

![Screenshot 2024-05-13 at 11 05 27 PM](https://github.com/form-atoms/list-atom/assets/14316332/bef14fb3-7bc6-46ab-95e4-b9cb1d73af5f)
![Screenshot 2024-05-13 at 11 02 09 PM](https://github.com/form-atoms/list-atom/assets/14316332/2341cfe4-b8df-4252-a22d-f6ae8237f470)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by pgangwani** [comment]
@MiroslavPetrik : Please review this issue and PR <minor fix>. Let me know if any question.

**Comment by MiroslavPetrik** [comment]
The useFieldInitialValue hook indeed accepts the `RESET` symbol, so the request seems valid.
But looking at it practically, I would advise not to use it in such a way.
The purpose of the `initialValue` prop is to set the hydrated data, e.g. when you fetch that from the server.
The `RESET` symbol value, is to clear any changes back to the first hydrated value, which best is done via the [reset action.](https://github.com/form-atoms/form-atoms?tab=readme-ov-file#usefieldactions)

Do you really need it?

**Comment by MiroslavPetrik** [comment]
https://github.com/form-atoms/list-atom/pull/9#issuecomment-2348561417
